# Generated by Django 5.2.4 on 2025-07-21 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synthesis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Netlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='netlists/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verilog_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='netlists', to='synthesis.verilogfile')),
            ],
        ),
    ]
