# Generated by Django 5.2.4 on 2025-07-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synthesis', '0002_netlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='verilog_uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='verilogfile',
            name='library',
            field=models.FileField(blank=True, null=True, upload_to='verilog_uploads/'),
        ),
    ]
