# Generated by Django 5.2.4 on 2025-07-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synthesis', '0003_libraryfile_verilogfile_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='verilogfile',
            name='original_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
