/* Generated by Yosys 0.36+42 (git sha1 70d35314d, clang 11.0.1-2 -fPIC -Os) */

(* src = "/data/full_adder_simple.v:1.1-10.10" *)
(* top =  1  *)
module full_adder_simple(A, B, C, Sum, Carry);
  (* src = "/data/full_adder_simple.v:8.21-8.26" *)
  wire _00_;
  (* src = "/data/full_adder_simple.v:8.31-8.36" *)
  wire _01_;
  (* src = "/data/full_adder_simple.v:8.41-8.46" *)
  wire _02_;
  (* src = "/data/full_adder_simple.v:8.20-8.37" *)
  wire _03_;
  (* src = "/data/full_adder_simple.v:7.18-7.23" *)
  wire _04_;
  (* src = "/data/full_adder_simple.v:2.16-2.17" *)
  input A;
  wire A;
  (* src = "/data/full_adder_simple.v:2.19-2.20" *)
  input B;
  wire B;
  (* src = "/data/full_adder_simple.v:2.22-2.23" *)
  input C;
  wire C;
  (* src = "/data/full_adder_simple.v:3.22-3.27" *)
  output Carry;
  wire Carry;
  (* src = "/data/full_adder_simple.v:3.17-3.20" *)
  output Sum;
  wire Sum;
  (* src = "/data/full_adder_simple.v:7.18-7.27" *)
  \$_XOR_  _05_ (
    .A(_04_),
    .B(C),
    .Y(Sum)
  );
  (* src = "/data/full_adder_simple.v:7.18-7.23" *)
  \$_XOR_  _06_ (
    .A(A),
    .B(B),
    .Y(_04_)
  );
  (* src = "/data/full_adder_simple.v:8.20-8.47" *)
  \$_OR_  _07_ (
    .A(_03_),
    .B(_02_),
    .Y(Carry)
  );
  (* src = "/data/full_adder_simple.v:8.20-8.37" *)
  \$_OR_  _08_ (
    .A(_00_),
    .B(_01_),
    .Y(_03_)
  );
  (* src = "/data/full_adder_simple.v:8.41-8.46" *)
  \$_AND_  _09_ (
    .A(B),
    .B(C),
    .Y(_02_)
  );
  (* src = "/data/full_adder_simple.v:8.31-8.36" *)
  \$_AND_  _10_ (
    .A(A),
    .B(C),
    .Y(_01_)
  );
  (* src = "/data/full_adder_simple.v:8.21-8.26" *)
  \$_AND_  _11_ (
    .A(A),
    .B(B),
    .Y(_00_)
  );
endmodule
