/* Generated by Yosys 0.36+42 (git sha1 70d35314d, clang 11.0.1-2 -fPIC -Os) */

(* src = "/data/riscv_core.v:20.1-51.10" *)
(* top =  1  *)
module riscv_core(clk, reset);
  (* src = "/data/riscv_core.v:20.30-20.33" *)
  input clk;
  wire clk;
  (* src = "/data/riscv_core.v:20.46-20.51" *)
  input reset;
  wire reset;
endmodule
