/* Generated by Yosys 0.36+42 (git sha1 70d35314d, clang 11.0.1-2 -fPIC -Os) */

(* src = "/data/full_adder.v:1.1-60.10" *)
(* top =  1  *)
module full_adder(A, B, C, Clock, Scan_clk, Scan_en, cg_en, gen_clk_mux, Sum, Carry);
  (* unused_bits = "0" *)
  wire _00_;
  (* unused_bits = "0" *)
  wire _01_;
  (* unused_bits = "0" *)
  wire _02_;
  (* unused_bits = "0" *)
  wire _03_;
  (* unused_bits = "0" *)
  wire _04_;
  (* src = "/data/full_adder.v:2.16-2.17" *)
  input A;
  wire A;
  (* src = "/data/full_adder.v:2.19-2.20" *)
  input B;
  wire B;
  (* src = "/data/full_adder.v:2.22-2.23" *)
  input C;
  wire C;
  (* src = "/data/full_adder.v:11.10-11.13" *)
  wire CLK;
  (* src = "/data/full_adder.v:5.22-5.27" *)
  output Carry;
  wire Carry;
  (* src = "/data/full_adder.v:3.16-3.21" *)
  input Clock;
  wire Clock;
  (* src = "/data/full_adder.v:3.23-3.31" *)
  input Scan_clk;
  wire Scan_clk;
  (* src = "/data/full_adder.v:3.33-3.40" *)
  input Scan_en;
  wire Scan_en;
  (* src = "/data/full_adder.v:5.17-5.20" *)
  output Sum;
  wire Sum;
  (* src = "/data/full_adder.v:4.16-4.21" *)
  input cg_en;
  wire cg_en;
  (* src = "/data/full_adder.v:4.23-4.34" *)
  input gen_clk_mux;
  wire gen_clk_mux;
  (* src = "/data/full_adder.v:9.10-9.19" *)
  wire mux_clock;
  (* src = "/data/full_adder.v:15.14-15.17" *)
  wire n10;
  (* src = "/data/full_adder.v:15.19-15.22" *)
  wire n11;
  (* src = "/data/full_adder.v:15.24-15.27" *)
  wire n12;
  (* src = "/data/full_adder.v:15.29-15.32" *)
  wire n13;
  (* src = "/data/full_adder.v:13.10-13.12" *)
  wire n4;
  (* src = "/data/full_adder.v:13.14-13.16" *)
  wire n5;
  (* src = "/data/full_adder.v:13.18-13.20" *)
  wire n6;
  (* src = "/data/full_adder.v:14.10-14.12" *)
  wire n7;
  (* src = "/data/full_adder.v:14.14-14.16" *)
  wire n8;
  (* src = "/data/full_adder.v:15.10-15.12" *)
  wire n9;
  (* src = "/data/full_adder.v:54.5-55.26" *)
  DFF_X1 _05_ (
    .CK(CLK),
    .D(n13),
    .Q(Carry),
    .QN(_01_)
  );
  (* src = "/data/full_adder.v:52.5-53.23" *)
  DFF_X1 _06_ (
    .CK(CLK),
    .D(n8),
    .Q(Sum),
    .QN(_02_)
  );
  (* src = "/data/full_adder.v:33.5-34.20" *)
  DFF_X1 _07_ (
    .CK(CLK),
    .D(C),
    .Q(n6),
    .QN(_03_)
  );
  (* src = "/data/full_adder.v:31.5-32.20" *)
  DFF_X1 _08_ (
    .CK(CLK),
    .D(B),
    .Q(n5),
    .QN(_04_)
  );
  (* src = "/data/full_adder.v:29.5-30.20" *)
  DFF_X1 _09_ (
    .CK(CLK),
    .D(A),
    .Q(n4),
    .QN(_00_)
  );
  (* src = "/data/full_adder.v:19.24-19.52" *)
  \$_MUX_  _10_ (
    .A(Clock),
    .B(Scan_clk),
    .S(Scan_en),
    .Y(mux_clock)
  );
  (* src = "/data/full_adder.v:48.18-48.27" *)
  \$_OR_  _11_ (
    .A(n12),
    .B(n11),
    .Y(n13)
  );
  (* src = "/data/full_adder.v:47.18-47.26" *)
  \$_OR_  _12_ (
    .A(n9),
    .B(n10),
    .Y(n12)
  );
  (* src = "/data/full_adder.v:46.18-46.25" *)
  \$_AND_  _13_ (
    .A(n4),
    .B(n6),
    .Y(n11)
  );
  (* src = "/data/full_adder.v:45.18-45.25" *)
  \$_AND_  _14_ (
    .A(n4),
    .B(n5),
    .Y(n10)
  );
  (* src = "/data/full_adder.v:44.18-44.25" *)
  \$_AND_  _15_ (
    .A(n5),
    .B(n6),
    .Y(n9)
  );
  (* src = "/data/full_adder.v:22.26-22.43" *)
  \$_AND_  _16_ (
    .A(mux_clock),
    .B(cg_en),
    .Y(CLK)
  );
  (* src = "/data/full_adder.v:42.17-42.24" *)
  \$_XOR_  _17_ (
    .A(n7),
    .B(n6),
    .Y(n8)
  );
  (* src = "/data/full_adder.v:41.17-41.24" *)
  \$_XOR_  _18_ (
    .A(n4),
    .B(n5),
    .Y(n7)
  );
endmodule
