/* Generated by Yosys 0.36+42 (git sha1 70d35314d, clang 11.0.1-2 -fPIC -Os) */

(* src = "/data/fulladder.v:1.1-58.10" *)
(* top =  1  *)
module fulladder(A, B, C, Sum, Carry, Clock, Scan_clk, Scan_en, cg_en, gen_clk_mux);
  (* src = "/data/fulladder.v:3.7-3.8" *)
  input A;
  wire A;
  (* src = "/data/fulladder.v:3.9-3.10" *)
  input B;
  wire B;
  (* src = "/data/fulladder.v:3.11-3.12" *)
  input C;
  wire C;
  (* src = "/data/fulladder.v:6.61-6.64" *)
  wire CLK;
  (* src = "/data/fulladder.v:4.12-4.17" *)
  output Carry;
  wire Carry;
  (* src = "/data/fulladder.v:3.13-3.18" *)
  input Clock;
  wire Clock;
  (* src = "/data/fulladder.v:3.19-3.27" *)
  input Scan_clk;
  wire Scan_clk;
  (* src = "/data/fulladder.v:3.28-3.35" *)
  input Scan_en;
  wire Scan_en;
  (* src = "/data/fulladder.v:4.8-4.11" *)
  output Sum;
  wire Sum;
  (* src = "/data/fulladder.v:3.36-3.41" *)
  input cg_en;
  wire cg_en;
  (* src = "/data/fulladder.v:6.76-6.87" *)
  wire gated_clock;
  (* src = "/data/fulladder.v:3.43-3.54" *)
  input gen_clk_mux;
  wire gen_clk_mux;
  (* src = "/data/fulladder.v:6.66-6.75" *)
  wire mux_clock;
  (* src = "/data/fulladder.v:6.31-6.34" *)
  wire n10;
  (* src = "/data/fulladder.v:6.36-6.39" *)
  wire n11;
  (* src = "/data/fulladder.v:6.41-6.44" *)
  wire n12;
  (* src = "/data/fulladder.v:6.46-6.49" *)
  wire n13;
  (* src = "/data/fulladder.v:6.51-6.54" *)
  wire n14;
  (* src = "/data/fulladder.v:6.56-6.59" *)
  wire n15;
  (* src = "/data/fulladder.v:6.7-6.9" *)
  wire n4;
  (* src = "/data/fulladder.v:6.11-6.13" *)
  wire n5;
  (* src = "/data/fulladder.v:6.15-6.17" *)
  wire n6;
  (* src = "/data/fulladder.v:6.19-6.21" *)
  wire n7;
  (* src = "/data/fulladder.v:6.23-6.25" *)
  wire n8;
  (* src = "/data/fulladder.v:6.27-6.29" *)
  wire n9;
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/data/fulladder.v:55.8-55.32" *)
  BUF_X1 B1 (
    .A(n14),
    .Z(Carry)
  );
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/data/fulladder.v:56.8-56.30" *)
  BUF_X1 B2 (
    .A(n15),
    .Z(Sum)
  );
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/data/fulladder.v:20.8-20.42" *)
  BUF_X1 CLK_B1 (
    .A(gated_clock),
    .Z(CLK)
  );
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/data/fulladder.v:32.9-32.35" *)
  XOR2_X1 G1 (
    .A(n4),
    .B(n5),
    .Z(n7)
  );
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/data/fulladder.v:33.9-33.35" *)
  XOR2_X1 G2 (
    .A(n7),
    .B(n6),
    .Z(n8)
  );
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/data/fulladder.v:39.9-39.38" *)
  AND2_X1 G3 (
    .A1(n5),
    .A2(n6),
    .ZN(n9)
  );
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/data/fulladder.v:40.9-40.39" *)
  AND2_X1 G4 (
    .A1(n4),
    .A2(n5),
    .ZN(n10)
  );
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/data/fulladder.v:41.9-41.39" *)
  AND2_X1 G5 (
    .A1(n4),
    .A2(n6),
    .ZN(n11)
  );
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/data/fulladder.v:46.8-46.40" *)
  OR2_X1 G6 (
    .A1(n12),
    .A2(n11),
    .ZN(n13)
  );
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/data/fulladder.v:45.8-45.39" *)
  OR2_X1 G7 (
    .A1(n9),
    .A2(n10),
    .ZN(n12)
  );
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/data/fulladder.v:17.9-17.59" *)
  AND2_X1 gate (
    .A1(mux_clock),
    .A2(cg_en),
    .ZN(gated_clock)
  );
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/data/fulladder.v:14.9-14.66" *)
  MUX2_X1 mux1 (
    .A(Clock),
    .B(Scan_clk),
    .S(Scan_en),
    .Z(mux_clock)
  );
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/data/fulladder.v:25.8-25.45" *)
  DFF_X1 reg1 (
    .CK(CLK),
    .D(A),
    .Q(n4)
  );
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/data/fulladder.v:26.8-26.45" *)
  DFF_X1 reg2 (
    .CK(CLK),
    .D(B),
    .Q(n5)
  );
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/data/fulladder.v:27.8-27.45" *)
  DFF_X1 reg3 (
    .CK(CLK),
    .D(C),
    .Q(n6)
  );
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/data/fulladder.v:50.8-50.48" *)
  DFF_X1 reg4 (
    .CK(CLK),
    .D(n13),
    .Q(n14)
  );
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/data/fulladder.v:51.8-51.48" *)
  DFF_X1 reg5 (
    .CK(CLK),
    .D(n8),
    .Q(n15)
  );
endmodule
