/* Generated by Yosys 0.36+42 (git sha1 70d35314d, clang 11.0.1-2 -fPIC -Os) */

(* src = "/data/4_bit_adder.v:1.1-17.10" *)
module counter_4bit(clk, rst, en, cnt);
  wire _00_;
  wire _01_;
  (* force_downto = 32'd1 *)
  (* src = "/data/4_bit_adder.v:13.16-13.23|/usr/local/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [3:0] _02_;
  (* force_downto = 32'd1 *)
  (* src = "/data/4_bit_adder.v:13.16-13.23|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [3:0] _03_;
  (* src = "/data/4_bit_adder.v:2.16-2.19" *)
  input clk;
  wire clk;
  (* src = "/data/4_bit_adder.v:5.22-5.25" *)
  output [3:0] cnt;
  reg [3:0] cnt;
  (* src = "/data/4_bit_adder.v:4.16-4.18" *)
  input en;
  wire en;
  (* src = "/data/4_bit_adder.v:3.16-3.19" *)
  input rst;
  wire rst;
  assign _02_[0] = ~cnt[0];
  assign _00_ = cnt[1] & cnt[0];
  assign _01_ = _00_ & cnt[2];
  assign _03_[3] = _01_ ^ cnt[3];
  assign _03_[1] = cnt[1] ^ cnt[0];
  assign _03_[2] = _00_ ^ cnt[2];
  (* src = "/data/4_bit_adder.v:9.1-15.4" *)
  always @(posedge clk, posedge rst)
    if (rst) cnt[0] <= 1'h0;
    else if (en) cnt[0] <= _02_[0];
  (* src = "/data/4_bit_adder.v:9.1-15.4" *)
  always @(posedge clk, posedge rst)
    if (rst) cnt[1] <= 1'h0;
    else if (en) cnt[1] <= _03_[1];
  (* src = "/data/4_bit_adder.v:9.1-15.4" *)
  always @(posedge clk, posedge rst)
    if (rst) cnt[2] <= 1'h0;
    else if (en) cnt[2] <= _03_[2];
  (* src = "/data/4_bit_adder.v:9.1-15.4" *)
  always @(posedge clk, posedge rst)
    if (rst) cnt[3] <= 1'h0;
    else if (en) cnt[3] <= _03_[3];
  assign _02_[3:1] = cnt[3:1];
  assign _03_[0] = _02_[0];
endmodule
