/* Generated by Yosys 0.36+42 (git sha1 70d35314d, clang 11.0.1-2 -fPIC -Os) */

module counter_4bit(clk, rst, en, cnt);
  wire _00_;
  wire _01_;
  wire [3:0] _02_;
  wire [3:0] _03_;
  input clk;
  wire clk;
  output [3:0] cnt;
  reg [3:0] cnt;
  input en;
  wire en;
  input rst;
  wire rst;
  assign _02_[0] = ~cnt[0];
  assign _00_ = cnt[1] & cnt[0];
  assign _01_ = _00_ & cnt[2];
  assign _03_[3] = _01_ ^ cnt[3];
  assign _03_[1] = cnt[1] ^ cnt[0];
  assign _03_[2] = _00_ ^ cnt[2];
  always @(posedge clk, posedge rst)
    if (rst) cnt[0] <= 1'h0;
    else if (en) cnt[0] <= _02_[0];
  always @(posedge clk, posedge rst)
    if (rst) cnt[1] <= 1'h0;
    else if (en) cnt[1] <= _03_[1];
  always @(posedge clk, posedge rst)
    if (rst) cnt[2] <= 1'h0;
    else if (en) cnt[2] <= _03_[2];
  always @(posedge clk, posedge rst)
    if (rst) cnt[3] <= 1'h0;
    else if (en) cnt[3] <= _03_[3];
  assign _02_[3:1] = cnt[3:1];
  assign _03_[0] = _02_[0];
endmodule
