/* Generated by Yosys 0.36+42 (git sha1 70d35314d, clang 11.0.1-2 -fPIC -Os) */

(* src = "/data/counter_4bit.v:1.1-17.10" *)
(* top =  1  *)
module counter_4bit(clk, rst, en, cnt);
  (* src = "/data/counter_4bit.v:13.16-13.23|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire _00_;
  (* src = "/data/counter_4bit.v:13.16-13.23|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire _01_;
  (* src = "/data/counter_4bit.v:13.16-13.23|/usr/local/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire _02_;
  (* src = "/data/counter_4bit.v:13.16-13.23|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire _03_;
  (* src = "/data/counter_4bit.v:13.16-13.23|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire _04_;
  (* src = "/data/counter_4bit.v:13.16-13.23|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire _05_;
  (* unused_bits = "0" *)
  wire _06_;
  (* unused_bits = "0" *)
  wire _07_;
  (* unused_bits = "0" *)
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  (* src = "/data/counter_4bit.v:2.16-2.19" *)
  input clk;
  wire clk;
  (* src = "/data/counter_4bit.v:5.22-5.25" *)
  output [3:0] cnt;
  wire [3:0] cnt;
  (* src = "/data/counter_4bit.v:4.16-4.18" *)
  input en;
  wire en;
  (* src = "/data/counter_4bit.v:3.16-3.19" *)
  input rst;
  wire rst;
  \$_NOT_  _14_ (
    .A(rst),
    .Y(_09_)
  );
  (* src = "/data/counter_4bit.v:9.1-15.4" *)
  DFFR_X1 _15_ (
    .CK(clk),
    .D(_10_),
    .Q(cnt[0]),
    .QN(_02_),
    .RN(_09_)
  );
  (* src = "/data/counter_4bit.v:9.1-15.4" *)
  DFFR_X1 _16_ (
    .CK(clk),
    .D(_11_),
    .Q(cnt[1]),
    .QN(_08_),
    .RN(_09_)
  );
  (* src = "/data/counter_4bit.v:9.1-15.4" *)
  DFFR_X1 _17_ (
    .CK(clk),
    .D(_12_),
    .Q(cnt[2]),
    .QN(_07_),
    .RN(_09_)
  );
  (* src = "/data/counter_4bit.v:9.1-15.4" *)
  DFFR_X1 _18_ (
    .CK(clk),
    .D(_13_),
    .Q(cnt[3]),
    .QN(_06_),
    .RN(_09_)
  );
  \$_MUX_  _19_ (
    .A(cnt[0]),
    .B(_02_),
    .S(en),
    .Y(_10_)
  );
  \$_MUX_  _20_ (
    .A(cnt[1]),
    .B(_03_),
    .S(en),
    .Y(_11_)
  );
  \$_MUX_  _21_ (
    .A(cnt[2]),
    .B(_04_),
    .S(en),
    .Y(_12_)
  );
  \$_MUX_  _22_ (
    .A(cnt[3]),
    .B(_05_),
    .S(en),
    .Y(_13_)
  );
  (* src = "/data/counter_4bit.v:13.16-13.23|/usr/local/bin/../share/yosys/techmap.v:289.13-289.25" *)
  \$_XOR_  _23_ (
    .A(cnt[2]),
    .B(_00_),
    .Y(_04_)
  );
  (* src = "/data/counter_4bit.v:13.16-13.23|/usr/local/bin/../share/yosys/techmap.v:289.13-289.25" *)
  \$_XOR_  _24_ (
    .A(cnt[3]),
    .B(_01_),
    .Y(_05_)
  );
  (* src = "/data/counter_4bit.v:13.16-13.23|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  \$_AND_  _25_ (
    .A(cnt[1]),
    .B(cnt[0]),
    .Y(_00_)
  );
  (* src = "/data/counter_4bit.v:13.16-13.23|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)
  \$_AND_  _26_ (
    .A(cnt[2]),
    .B(_00_),
    .Y(_01_)
  );
  (* src = "/data/counter_4bit.v:13.16-13.23|/usr/local/bin/../share/yosys/techmap.v:289.13-289.25" *)
  \$_XOR_  _27_ (
    .A(cnt[1]),
    .B(cnt[0]),
    .Y(_03_)
  );
endmodule
