/* Generated by Yosys 0.36+42 (git sha1 70d35314d, clang 11.0.1-2 -fPIC -Os) */

(* src = "/data/full_adder_seq.v:1.1-20.10" *)
(* top =  1  *)
module full_adder_seq(A, B, C, clk, Sum, Carry);
  (* src = "/data/full_adder_seq.v:12.26-12.31" *)
  wire _00_;
  (* src = "/data/full_adder_seq.v:12.36-12.41" *)
  wire _01_;
  (* src = "/data/full_adder_seq.v:12.46-12.51" *)
  wire _02_;
  (* unused_bits = "0" *)
  wire _03_;
  (* unused_bits = "0" *)
  wire _04_;
  (* src = "/data/full_adder_seq.v:12.25-12.42" *)
  wire _05_;
  (* src = "/data/full_adder_seq.v:11.23-11.28" *)
  wire _06_;
  (* src = "/data/full_adder_seq.v:2.16-2.17" *)
  input A;
  wire A;
  (* src = "/data/full_adder_seq.v:2.19-2.20" *)
  input B;
  wire B;
  (* src = "/data/full_adder_seq.v:2.22-2.23" *)
  input C;
  wire C;
  (* src = "/data/full_adder_seq.v:4.21-4.26" *)
  output Carry;
  wire Carry;
  (* src = "/data/full_adder_seq.v:4.16-4.19" *)
  output Sum;
  wire Sum;
  (* src = "/data/full_adder_seq.v:8.20-8.30" *)
  wire carry_comb;
  (* src = "/data/full_adder_seq.v:3.16-3.19" *)
  input clk;
  wire clk;
  (* src = "/data/full_adder_seq.v:8.10-8.18" *)
  wire sum_comb;
  (* src = "/data/full_adder_seq.v:15.5-18.8" *)
  DFF_X1 _07_ (
    .CK(clk),
    .D(sum_comb),
    .Q(Sum),
    .QN(_04_)
  );
  (* src = "/data/full_adder_seq.v:15.5-18.8" *)
  DFF_X1 _08_ (
    .CK(clk),
    .D(carry_comb),
    .Q(Carry),
    .QN(_03_)
  );
  (* src = "/data/full_adder_seq.v:11.23-11.32" *)
  \$_XOR_  _09_ (
    .A(_06_),
    .B(C),
    .Y(sum_comb)
  );
  (* src = "/data/full_adder_seq.v:11.23-11.28" *)
  \$_XOR_  _10_ (
    .A(A),
    .B(B),
    .Y(_06_)
  );
  (* src = "/data/full_adder_seq.v:12.25-12.52" *)
  \$_OR_  _11_ (
    .A(_05_),
    .B(_02_),
    .Y(carry_comb)
  );
  (* src = "/data/full_adder_seq.v:12.25-12.42" *)
  \$_OR_  _12_ (
    .A(_00_),
    .B(_01_),
    .Y(_05_)
  );
  (* src = "/data/full_adder_seq.v:12.46-12.51" *)
  \$_AND_  _13_ (
    .A(B),
    .B(C),
    .Y(_02_)
  );
  (* src = "/data/full_adder_seq.v:12.36-12.41" *)
  \$_AND_  _14_ (
    .A(A),
    .B(C),
    .Y(_01_)
  );
  (* src = "/data/full_adder_seq.v:12.26-12.31" *)
  \$_AND_  _15_ (
    .A(A),
    .B(B),
    .Y(_00_)
  );
endmodule
